export const DEFAULT_PRIMARY_INCOME = 8000;
export const DEFAULT_PARTNER_INCOME = 6800;
export const DEFAULT_PARTNER_BENEFIT = 900;
export const DEFAULT_GOAL_TARGET = 30000;
export const DEFAULT_MONTHLY_GOAL_SUGGESTION = 1200;
